### ISSUE TITLE
how to generate pb file

### ISSUE THREAD

**Issue by 123lifei** [wlguan/tf2-yolo3#1]
您好，我用您的工程训练了一些数据 但是不知怎么将结果ckpt.data 生成pb的部署文件啊
折腾两天了，实在不知咋那么生成，谢谢

**Comment by apxlwl** [comment]
@123lifei  你好，目前还不支持这个。不过这部分代码和tensorflow1.x是一样的，网上应该可以找到大把的教程。

**Comment by 123lifei** [comment]
@123lifei 您好 我用您的工程训练了一个模型 用的是(即train from scratch)的darknet53.conv.74 主要是检测人并将人分成不同的类别，但是发现效果不是太好，主要问题是有的场景下人员检测不到，有场景下人员检测挺好的这样的偏差，您觉的50000多数据，训练多少个epoch合适啊 ，您能给一些指导吗

**Comment by apxlwl** [comment]
@123lifei 我不太理解你的意思，如果使用的是darknet53.conv.74的话，在代码里会使用官方在coco上训练的权重，但是只会load backbone部分，并不是train from scratch，在VOC这部分pretrain对性能影响挺大的。至于你说的训练方面的细节就不好说了，不过可以在mAP不增长的时候降低一下lr。另外使用test augmentation也能有效提高召回率，这部分代码里也有。

**Comment by 123lifei** [comment]
@wlguan 能留个微信吗？我加您

Download Pretrained Convolutional Weights

For training we use convolutional weights that are pre-trained on Imagenet. We use weights from the darknet53 model. You can just download the weights for the convolutional layers here (76 MB).

wget https://pjreddie.com/media/files/darknet53.conv.74

上面这段是yoloV3官网的，darknet53.conv.74是在imageNet上训练过的模型吧  yolov3.weight 是在COCO上训练过的目标检测模型，这样对吧  我上次没有加载yolov3.weight 而是加载的darknet53.conv.74 
另外您测试过GIOU label_smooth等相关的tricks吗 能起到作用吗 谢谢回答了

**Comment by 123lifei** [comment]
@wlguan 另外我看到您的代码的中图像预处理的那块 图像是直接resize的 是不是应该按比例缩放 然后padding zero的啊，一般情况训练的时候 为了防止梯度溢出 会学习率warmup 一下 然后先训练最后一层的参数  然后再训练全部参数 我打算这样试一试 您觉的这样有可行性吗？

**Comment by apxlwl** [comment]
@123lifei 麻烦你给我发个邮件吧？我邮件回复你微信，guanwenlong@mail.dlut.edu.cn

**Comment by 123lifei** [comment]
@wlguan 我给您发邮件了
